import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / 'scripts' / 'site.py'


def run(*args):
    return subprocess.run(
        [sys.executable, str(SCRIPT), *map(str, args)],
        text=True,
        capture_output=True,
        check=False,
    )


class TemplateCliTests(unittest.TestCase):
    def test_list_templates_exposes_selection_metadata(self):
        result = run('list-templates')
        self.assertEqual(result.returncode, 0, result.stderr)
        output = json.loads(result.stdout)
        self.assertEqual({row['id'] for row in output['templates']}, {'static', 'browse', 'form', 'tool'})
        for row in output['templates']:
            self.assertTrue(row['semantic']['tasks'])
            self.assertTrue(row['strengths'])
            self.assertTrue(row['tradeoffs'])
            self.assertTrue(row['reject_conditions'])
            self.assertTrue(row['states'])
            self.assertTrue(row['validation_commands'])
            self.assertTrue(
                any('check-render.mjs' in command and '--contract' in command for command in row['validation_commands']),
                f"{row['id']} must declare a rendered task contract",
            )
            self.assertTrue((ROOT / 'tests' / 'contracts' / f"{row['id']}.json").is_file())

    def test_inspect_template_returns_one_complete_card(self):
        result = run('inspect-template', 'tool')
        self.assertEqual(result.returncode, 0, result.stderr)
        output = json.loads(result.stdout)
        self.assertEqual(output['id'], 'tool')
        self.assertIn('local-persistence', output['patterns'])
        self.assertIn('error', output['states'])

    def test_every_template_initializes_without_skipping_discovery(self):
        for template in ('static', 'browse', 'form', 'tool'):
            with self.subTest(template=template), tempfile.TemporaryDirectory() as folder:
                destination = Path(folder) / 'project'
                result = run('init', destination, '--template', template, '--title', '测试项目')
                self.assertEqual(result.returncode, 0, result.stderr)
                state = json.loads((destination / '.site' / 'state.json').read_text(encoding='utf-8'))
                self.assertEqual(state['stage'], 'discovering')
                self.assertTrue(state['visual_required'])
                self.assertFalse(state['development_authorized'])
                self.assertTrue((destination / 'web' / 'index.html').is_file())

    def test_init_does_not_generate_runner_or_package_by_default(self):
        with tempfile.TemporaryDirectory() as folder:
            destination = Path(folder) / 'project'
            result = run('init', destination, '--template', 'static', '--title', '测试项目')
            self.assertEqual(result.returncode, 0, result.stderr)
            # Runner scripts and package must NOT be generated by default
            self.assertFalse((destination / 'start.bat').exists())
            self.assertFalse((destination / 'start.sh').exists())
            self.assertEqual(list(destination.glob('*.zip')), [])

    def test_make_runner_generates_safe_runner_scripts_on_demand(self):
        for cmd in ('make-runner', 'helper-start-script'):
            with self.subTest(cmd=cmd), tempfile.TemporaryDirectory() as folder:
                destination = Path(folder) / 'project'
                run('init', destination, '--template', 'static', '--title', '测试项目')
                result = run(cmd, destination)
                self.assertEqual(result.returncode, 0, result.stderr)
                output = json.loads(result.stdout)
                self.assertIn('start.bat', output['scripts'])
                self.assertIn('start.sh', output['scripts'])

                bat = destination / 'start.bat'
                sh = destination / 'start.sh'
                self.assertTrue(bat.is_file())
                self.assertTrue(sh.is_file())

                bat_content = bat.read_text(encoding='utf-8')
                self.assertIn('http.server', bat_content)
                self.assertIn('start http://localhost:', bat_content)
                self.assertIn('npx', bat_content)

                sh_content = sh.read_text(encoding='utf-8')
                self.assertIn('http.server', sh_content)
                self.assertIn('PORT', sh_content)
                self.assertIn('npx', sh_content)

    def test_package_generates_clean_distribution_zip_on_demand(self):
        import zipfile
        for cmd in ('package', 'helper-package'):
            with self.subTest(cmd=cmd), tempfile.TemporaryDirectory() as folder:
                destination = Path(folder) / 'project'
                run('init', destination, '--template', 'tool', '--title', '测试项目')
                # Also generate runner scripts
                run('make-runner', destination)

                # Add some development / unwanted files that should be excluded
                (destination / '.git').mkdir()
                (destination / '.git' / 'config').write_text('dummy', encoding='utf-8')
                (destination / 'node_modules').mkdir()
                (destination / 'node_modules' / 'dummy.txt').write_text('dummy', encoding='utf-8')
                (destination / '__pycache__').mkdir()
                (destination / '__pycache__' / 'dummy.pyc').write_bytes(b'dummy')

                zip_out = Path(folder) / 'dist.zip'
                result = run(cmd, destination, zip_out)
                self.assertEqual(result.returncode, 0, result.stderr)
                output = json.loads(result.stdout)
                self.assertEqual(output['archive'], str(zip_out))
                self.assertTrue(zip_out.is_file())

                with zipfile.ZipFile(zip_out, 'r') as zf:
                    names = zf.namelist()
                    # Clean web files and runners included
                    self.assertIn('web/index.html', names)
                    self.assertIn('web/style.css', names)
                    self.assertIn('web/app.js', names)
                    self.assertIn('start.bat', names)
                    self.assertIn('start.sh', names)

                    # Excluded internal development files
                    self.assertFalse(any(n.startswith('.git') for n in names))
                    self.assertFalse(any(n.startswith('.site') for n in names))
                    self.assertFalse(any(n.startswith('node_modules') for n in names))
                    self.assertFalse(any('__pycache__' in n for n in names))

    def test_package_default_output_and_internal_zip(self):
        with tempfile.TemporaryDirectory() as folder:
            destination = Path(folder) / 'my-site'
            run('init', destination, '--template', 'static', '--title', '测试项目')

            # Default output: <parent>/my-site.zip
            result = run('package', destination)
            self.assertEqual(result.returncode, 0, result.stderr)
            expected_zip = Path(folder) / 'my-site.zip'
            self.assertTrue(expected_zip.is_file())

            # Output inside destination: should not recursively pack itself
            internal_zip = destination / 'dist.zip'
            result2 = run('package', destination, '--output', internal_zip)
            self.assertEqual(result2.returncode, 0, result2.stderr)
            self.assertTrue(internal_zip.is_file())

            import zipfile
            with zipfile.ZipFile(internal_zip, 'r') as zf:
                self.assertNotIn('dist.zip', zf.namelist())

    def test_runner_and_package_reject_invalid_directory(self):
        result_runner = run('make-runner', 'non_existent_directory_12345')
        self.assertNotEqual(result_runner.returncode, 0)

        result_pkg = run('package', 'non_existent_directory_12345')
        self.assertNotEqual(result_pkg.returncode, 0)

    def test_templates_hardened_with_social_meta_and_viewport_adaptation(self):
        template_root = ROOT / 'assets' / 'templates'
        for template_id in ('static', 'browse', 'form', 'tool'):
            with self.subTest(template=template_id):
                html_file = template_root / template_id / 'web' / 'index.html'
                css_file = template_root / template_id / 'web' / 'style.css'

                self.assertTrue(html_file.is_file())
                self.assertTrue(css_file.is_file())

                html_text = html_file.read_text(encoding='utf-8')
                css_text = css_file.read_text(encoding='utf-8')

                # 1. Social sharing cards (WeChat / OpenGraph Meta)
                self.assertIn('property="og:title"', html_text)
                self.assertIn('property="og:description"', html_text)
                self.assertIn('property="og:image"', html_text)
                self.assertIn('name="description"', html_text)

                # 2. Viewport height adaptation (min-height: 100vh, dvh or -webkit-fill-available)
                self.assertIn('min-height: 100vh', css_text)
                self.assertIn('min-height: 100dvh', css_text)

                # 3. Zero unreachable overseas dependencies
                for forbidden in ('fonts.googleapis.com', 'fonts.gstatic.com', 'unpkg.com', 'cdnjs.cloudflare.com', 'cdn.jsdelivr.net'):
                    self.assertNotIn(forbidden, html_text)
                    self.assertNotIn(forbidden, css_text)


if __name__ == '__main__':
    unittest.main()
